## Data Insights

#### Importing Required Libraries.

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Finding number of missing values

In [ ]:
data.isnull().sum()  # cheaking if any colomns is left empty or not.

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

# Analyzing the Dataset

In [ ]:
print(data.shape)

(118, 16)


In [ ]:
data.describe()

YEAR         JAN         FEB         MAR         APR  \
count   118.000000  118.000000  118.000000  118.000000  118.000000   
mean   1959.500000   12.218644   15.633898   36.670339  110.330508   
std      34.207699   15.473766   16.406290   30.063862   44.633452   
min    1901.000000    0.000000    0.000000    0.100000   13.100000   
25%    1930.250000    2.175000    4.700000   18.100000   74.350000   
50%    1959.500000    5.800000    8.350000   28.400000  110.400000   
75%    1988.750000   18.175000   21.400000   49.825000  136.450000   
max    2018.000000   83.500000   79.000000  217.200000  238.000000   

              MAY          JUN          JUL          AUG         SEP  \
count  118.000000   118.000000   118.000000   118.000000  118.000000   
mean   228.644915   651.617797   698.220339   430.369492  246.207627   
std    147.548778   186.181363   228.988966   181.980463  121.901131   
min     53.400000   196.800000   167.500000   178.600000   41.300000   
25%    125.050000   535.550000   533.200000   316.725000  155.425000   
50%    184.600000   625.600000   691.650000   386.250000  223.550000   
75%    264.875000   786.975000   832.425000   500.100000  334.500000   
max    738.800000  1098.200000  1526.500000  1398.900000  526.700000   

              OCT         NOV         DEC   ANNUAL RAINFALL  
count  118.000000  118.000000  118.000000        118.000000  
mean   293.207627  162.311017   40.009322       2925.405085  
std     93.705253   83.200485   36.676330        452.169407  
min     68.500000   31.500000    0.100000       2068.800000  
25%    222.125000   93.025000   10.350000       2613.525000  
50%    284.300000  152.450000   31.100000       2934.300000  
75%    355.150000  218.325000   54.025000       3170.400000  
max    567.900000  365.600000  202.300000       4473.000000

In [ ]:
data.cov()

YEAR         JAN         FEB          MAR  \
YEAR              1170.166667 -119.378632    2.176923   -13.207265   
JAN               -119.378632  239.437427    4.979192    36.577053   
FEB                  2.176923    4.979192  269.166362   121.027766   
MAR                -13.207265   36.577053  121.027766   903.835779   
APR                132.625641   24.039512   90.585966    99.315784   
MAY               -301.126068  163.062403 -202.129655  -456.721990   
JUN              -1114.149145  545.574281  165.293580   106.348567   
JUL              -1749.953846  121.970900   21.748364   126.186249   
AUG                274.983761   24.434163   69.442838   232.033874   
SEP                448.915812 -214.094844  132.629654   527.184758   
OCT                -96.876496  -50.812451   81.684355   -64.980285   
NOV               -370.360256  -14.205421 -222.332684   -81.573089   
DEC               -155.123504  -50.968209  -76.434079    28.990108   
 ANNUAL RAINFALL -3063.344444  830.154092  455.913330  1578.305793   

                          APR           MAY           JUN           JUL  \
YEAR               132.625641   -301.126068  -1114.149145  -1749.953846   
JAN                 24.039512    163.062403    545.574281    121.970900   
FEB                 90.585966   -202.129655    165.293580     21.748364   
MAR                 99.315784   -456.721990    106.348567    126.186249   
APR               1992.145044   -754.490185    606.540393    153.070058   
MAY               -754.490185  21770.641812     33.929279  -1571.703571   
JUN                606.540393     33.929279  34663.499937   4047.567071   
JUL                153.070058  -1571.703571   4047.567071  52435.946420   
AUG               -388.591540  -3340.586652   -492.944239   6436.876865   
SEP                 70.336859   2101.892304  -1194.576633   5846.347194   
OCT                473.330962   2725.149056     20.161145    541.214459   
NOV                 82.464276   1165.417193    247.329460   -543.479371   
DEC               -180.710372   -638.978371   -581.699654   -113.988396   
 ANNUAL RAINFALL  2267.590185  20997.420795  38170.332986  67508.201520   

                           AUG           SEP          OCT          NOV  \
YEAR                274.983761    448.915812   -96.876496  -370.360256   
JAN                  24.434163   -214.094844   -50.812451   -14.205421   
FEB                  69.442838    132.629654    81.684355  -222.332684   
MAR                 232.033874    527.184758   -64.980285   -81.573089   
APR                -388.591540     70.336859   473.330962    82.464276   
MAY               -3340.586652   2101.892304  2725.149056  1165.417193   
JUN                -492.944239  -1194.576633    20.161145   247.329460   
JUL                6436.876865   5846.347194   541.214459  -543.479371   
AUG               33116.888805   2178.762799 -3094.959423 -1706.808293   
SEP                2178.762799  14859.885839  -369.500828  -280.077350   
OCT               -3094.959423   -369.500828  8780.674386  -187.580256   
NOV               -1706.808293   -280.077350  -187.580256  6922.320647   
DEC                 948.365073    -49.210243  -134.262978   215.801948   
 ANNUAL RAINFALL  33987.052721  23610.285602  8722.467910  5597.319516   

                          DEC   ANNUAL RAINFALL  
YEAR              -155.123504      -3063.344444  
JAN                -50.968209        830.154092  
FEB                -76.434079        455.913330  
MAR                 28.990108       1578.305793  
APR               -180.710372       2267.590185  
MAY               -638.978371      20997.420795  
JUN               -581.699654      38170.332986  
JUL               -113.988396      67508.201520  
AUG                948.365073      33987.052721  
SEP                -49.210243      23610.285602  
OCT               -134.262978       8722.467910  
NOV                215.801948       5597.319516  
DEC               1345.153160        712.560721  
 ANNUAL RAINFALL   712.560721     204

In [ ]:
data.corr()

YEAR       JAN       FEB       MAR       APR       MAY  \
YEAR              1.000000 -0.225531  0.003879 -0.012842  0.086865 -0.059661   
JAN              -0.225531  1.000000  0.019613  0.078626  0.034807  0.071420   
FEB               0.003879  0.019613  1.000000  0.245375  0.123706 -0.083500   
MAR              -0.012842  0.078626  0.245375  1.000000  0.074014 -0.102961   
APR               0.086865  0.034807  0.123706  0.074014  1.000000 -0.114566   
MAY              -0.059661  0.071420 -0.083500 -0.102961 -0.114566  1.000000   
JUN              -0.174938  0.189375  0.054114  0.019000  0.072990  0.001235   
JUL              -0.223403  0.034423  0.005789  0.018330  0.014977 -0.046518   
AUG               0.044173  0.008677  0.023259  0.042411 -0.047842 -0.124412   
SEP               0.107655 -0.113502  0.066317  0.143850  0.012928  0.116860   
OCT              -0.030223 -0.035044  0.053133 -0.023066  0.113172  0.197102   
NOV              -0.130129 -0.011034 -0.162880 -0.032612  0.022206  0.094934   
DEC              -0.123643 -0.089809 -0.127025  0.026292 -0.110392 -0.118077   
 ANNUAL RAINFALL -0.198048  0.118648  0.061457  0.116103  0.112358  0.314723   

                       JUN       JUL       AUG       SEP       OCT       NOV  \
YEAR             -0.174938 -0.223403  0.044173  0.107655 -0.030223 -0.130129   
JAN               0.189375  0.034423  0.008677 -0.113502 -0.035044 -0.011034   
FEB               0.054114  0.005789  0.023259  0.066317  0.053133 -0.162880   
MAR               0.019000  0.018330  0.042411  0.143850 -0.023066 -0.032612   
APR               0.072990  0.014977 -0.047842  0.012928  0.113172  0.022206   
MAY               0.001235 -0.046518 -0.124412  0.116860  0.197102  0.094934   
JUN               1.000000  0.094939 -0.014549 -0.052634  0.001156  0.015967   
JUL               0.094939  1.000000  0.154467  0.209441  0.025223 -0.028526   
AUG              -0.014549  0.154467  1.000000  0.098215 -0.181496 -0.112729   
SEP              -0.052634  0.209441  0.098215  1.000000 -0.032348 -0.027615   
OCT               0.001156  0.025223 -0.181496 -0.032348  1.000000 -0.024060   
NOV               0.015967 -0.028526 -0.112729 -0.027615 -0.024060  1.000000   
DEC              -0.085188 -0.013573  0.142090 -0.011007 -0.039067  0.070720   
 ANNUAL RAINFALL  0.453407  0.651990  0.413036  0.428344  0.205861  0.148783   

                       DEC   ANNUAL RAINFALL  
YEAR             -0.123643         -0.198048  
JAN              -0.089809          0.118648  
FEB              -0.127025          0.061457  
MAR               0.026292          0.116103  
APR              -0.110392          0.112358  
MAY              -0.118077          0.314723  
JUN              -0.085188          0.453407  
JUL              -0.013573          0.651990  
AUG               0.142090          0.413036  
SEP              -0.011007          0.428344  
OCT              -0.039067          0.205861  
NOV               0.070720          0.148783  
DEC               1.000000          0.042967  
 ANNUAL RAINFALL  0.042967          1.000000

In [ ]:
# replacing the yes/no in floods coloumn by 1/0
data['FLOODS'].replace(['YES','NO'],[1,0],inplace=True)

In [ ]:
# Seperating the data which we are gonna use for prediction.
x=data.iloc[:,1:14]
x.head()

YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG    SEP    OCT  \
0  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5  197.7  266.9   
1  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8  491.6  358.4   
2  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2  341.8  354.1   
3  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8  222.7  328.1   
4  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6  217.2  383.5   

     NOV    DEC  
0  350.8   48.4  
1  158.3  121.5  
2  157.0   59.0  
3   33.9    3.3  
4   74.4    0.2

In [ ]:
# Now seperate the flood label from the dataset.
y=data.iloc[:,-1]
y

0      1
1      1
2      1
3      1
4      0
      ..
113    1
114    0
115    0
116    0
117    1
Name: FLOODS, Length: 118, dtype: int64

# Plotting the Data


In [ ]:
import matplotlib.pyplot as plt
# sets the backend of matplotlib to the 'inline' backend.
%matplotlib inline
c = data[['JUN','JUL','AUG','SEP']]
c.hist()
plt.show()
# How the rainfall index vary during rainy season

# Using sklearn to develop the ML Model

In [ ]:
# Scaling the data between 0 and 1.
from sklearn import preprocessing
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.        , 0.34371257, 0.56582278, ..., 0.39727673, 0.95570189,
        0.2388724 ],
       [0.00854701, 0.08023952, 0.03291139, ..., 0.5804966 , 0.37952709,
        0.60039565],
       [0.01709402, 0.03832335, 0.23544304, ..., 0.57188626, 0.37563604,
        0.29129575],
       ...,
       [0.98290598, 0.02874251, 0.04810127, ..., 0.31517821, 0.28105358,
        0.11622156],
       [0.99145299, 0.02275449, 0.08607595, ..., 0.24809772, 0.18258007,
        0.18793274],
       [1.        , 0.34850299, 0.65949367, ..., 0.57589107, 0.28105358,
        0.3214639 ]])

In [ ]:
#dividing the dataset into training dataset and test dataset.
from sklearn import model_selection,neighbors
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train.head()

YEAR  JAN   FEB    MAR    APR    MAY    JUN    JUL    AUG    SEP    OCT  \
96   1997  2.1   1.5   36.1   60.6  133.6  544.2  970.5  536.0  292.2  288.9   
107  2008  0.8  30.3  217.2  108.4   81.2  469.9  505.1  349.0  347.0  343.4   
81   1982  0.7   0.1   21.9   60.4  148.2  612.2  511.5  495.0   70.6  164.4   
55   1956  7.9  11.7   15.1  151.6  351.3  755.4  466.8  319.5  178.4  353.3   
65   1966  3.0   6.9   67.7  167.4   95.2  496.2  601.9  202.1  293.2  392.3   

       NOV   DEC  
96   298.4  88.4  
107   55.4  17.0  
81   127.5  10.8  
55   178.2   9.1  
65   245.4  50.5

In [ ]:
x_train.dtypes

YEAR      int64
JAN     float64
FEB     float64
MAR     float64
APR     float64
MAY     float64
JUN     float64
JUL     float64
AUG     float64
SEP     float64
OCT     float64
NOV     float64
DEC     float64
dtype: object

In [ ]:
x_test.head()

YEAR  JAN   FEB   MAR    APR    MAY    JUN    JUL    AUG    SEP    OCT  \
50   1951  6.6   6.5  41.6  175.9  148.5  774.1  544.6  190.6  313.8  250.6   
51   1952  5.2  48.2  20.8  112.2  214.6  576.7  430.0  413.6   57.4  339.6   
64   1965  9.1   0.9  28.3  109.8  214.5  597.7  465.1  296.1  150.1  183.7   
106  2007  0.5   5.6   7.3  138.5  192.7  705.9  966.3  489.6  526.7  357.2   
44   1945  4.4   9.9  12.7  104.1   53.4  549.8  704.0  351.8  110.9  253.8   

       NOV    DEC  
50   229.6   23.2  
51    49.6   66.9  
64   131.7  155.5  
106   87.4   11.9  
44   259.5   18.0

In [ ]:
# type casting.
y_train=y_train.astype('int')
y_train

96     1
107    0
81     0
55     0
65     0
      ..
33     0
4      0
99     0
61     1
85     0
Name: FLOODS, Length: 94, dtype: int32

In [ ]:
y_test=y_test.astype('int')
y_test

53     1
26     1
32     1
64     0
15     1
7      0
98     0
111    0
28     1
78     0
114    0
9      0
94     0
90     1
54     1
86     0
10     0
13     0
76     1
1      1
0      1
72     0
29     1
43     0
Name: FLOODS, dtype: int32

# Using Prediction Algorithms:

## KNN classifier to predict

In [ ]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
# Predicted chance of Flood.
print("Predicted Values for the Floods:")
y_predict=clf.predict(x_test)
y_predict

Predicted Values for the Floods:


array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0])

In [ ]:
print("Actual Values for the Floods:")
print(y_test)

Actual Values for the Floods:
53     1
26     1
32     1
64     0
15     1
7      0
98     0
111    0
28     1
78     0
114    0
9      0
94     0
90     1
54     1
86     0
10     0
13     0
76     1
1      1
0      1
72     0
29     1
43     0
Name: FLOODS, dtype: int32


In [ ]:
print("List of the Predicted Values:")
print(y_predict)

List of the Predicted Values:
[0 1 1 0 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0]


In [ ]:
# Scaling the dataset.
from sklearn.model_selection import cross_val_score,cross_val_predict
x_train_std= minmax.fit_transform(x_train)
x_test_std= minmax.fit_transform(x_test)
knn_acc=cross_val_score(clf,x_train_std,y_train,cv=3,scoring='accuracy',n_jobs=-1)
knn_proba=cross_val_predict(clf,x_train_std,y_train,cv=3,method='predict_proba')

In [ ]:
knn_acc

array([0.875     , 0.67741935, 0.77419355])

In [ ]:
knn_proba

array([[0.4, 0.6],
       [0.6, 0.4],
       [1. , 0. ],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.8, 0.2],
       [0.8, 0.2],
       [0.4, 0.6],
       [0.2, 0.8],
       [0.2, 0.8],
       [0.6, 0.4],
       [0.2, 0.8],
       [0.2, 0.8],
       [0.4, 0.6],
       [0.4, 0.6],
       [0.6, 0.4],
       [1. , 0. ],
       [0.8, 0.2],
       [1. , 0. ],
       [0.6, 0.4],
       [0.6, 0.4],
       [1. , 0. ],
       [0. , 1. ],
       [0.8, 0.2],
       [0.2, 0.8],
       [0.8, 0.2],
       [0.6, 0.4],
       [0.6, 0.4],
       [0. , 1. ],
       [0.2, 0.8],
       [0.6, 0.4],
       [0.4, 0.6],
       [1. , 0. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0.2, 0.8],
       [0.2, 0.8],
       [0.2, 0.8],
       [1. , 0. ],
       [0.6, 0.4],
       [1. , 0. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0.6, 0.4],
       [0.8, 0.2],
       [0.8, 0.2],
       [0.4, 0.6],
       [1. , 0. ],
       [0. , 1. ],
       [0.4, 0.6],
       [0.4, 0.6],
       [1. , 0. ],
       [0.2,

### How accurate is our model?

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\nAccuracy Score:%f"%(accuracy_score(y_test,y_predict)*100))
print("Recall Score:%f"%(recall_score(y_test,y_predict)*100))
print("ROC score:%f"%(roc_auc_score(y_test,y_predict)*100))
print(confusion_matrix(y_test,y_predict))


Accuracy Score:70.833333
Recall Score:63.636364
ROC score:70.279720
[[10  3]
 [ 4  7]]


## Logistic Regression to predict

In [ ]:
x_train_std=minmax.fit_transform(x_train)         # fit the values in between 0 and 1.
y_train_std=minmax.transform(x_test)

from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr_acc=cross_val_score(lr,x_train_std,y_train,cv=3,scoring='accuracy',n_jobs=-1)
lr_proba=cross_val_predict(lr,x_train_std,y_train,cv=3,method='predict_proba')

In [ ]:
lr_acc

array([0.875     , 0.80645161, 0.93548387])

In [ ]:
lr_proba

array([[0.32087356, 0.67912644],
       [0.66005794, 0.33994206],
       [0.69969751, 0.30030249],
       [0.50658702, 0.49341298],
       [0.54692215, 0.45307785],
       [0.61752775, 0.38247225],
       [0.37404139, 0.62595861],
       [0.47041428, 0.52958572],
       [0.32525191, 0.67474809],
       [0.39083255, 0.60916745],
       [0.41941002, 0.58058998],
       [0.27346897, 0.72653103],
       [0.28735535, 0.71264465],
       [0.32316686, 0.67683314],
       [0.39577063, 0.60422937],
       [0.62253257, 0.37746743],
       [0.74850717, 0.25149283],
       [0.77817018, 0.22182982],
       [0.4970778 , 0.5029222 ],
       [0.41610519, 0.58389481],
       [0.54869654, 0.45130346],
       [0.50807494, 0.49192506],
       [0.393891  , 0.606109  ],
       [0.47730087, 0.52269913],
       [0.3460429 , 0.6539571 ],
       [0.72919172, 0.27080828],
       [0.47986462, 0.52013538],
       [0.42305356, 0.57694644],
       [0.26944128, 0.73055872],
       [0.26589873, 0.73410127],
       [0.

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0])

In [ ]:
print(y_test.values)

[1 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 1 0]


In [ ]:
print("List of the Predicted Values:")
print(y_pred)

List of the Predicted Values:
[0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0]


### Accuracy and Efficiency of our Model

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\naccuracy score:%f"%(accuracy_score(y_test,y_pred)*100))
print("recall score:%f"%(recall_score(y_test,y_pred)*100))
print("roc score:%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))


accuracy score:87.500000
recall score:90.909091
roc score:87.762238
[[11  2]
 [ 1 10]]


## Support Vector Classification to predict

In [ ]:
from sklearn.svm import SVC
svc=SVC(kernel='rbf',probability=True)
svc_classifier=svc.fit(x_train,y_train)
svc_acc=cross_val_score(svc_classifier,x_train_std,y_train,cv=3,scoring="accuracy",n_jobs=-1)
svc_proba=cross_val_predict(svc_classifier,x_train_std,y_train,cv=3,method='predict_proba')

In [ ]:
svc_acc

array([0.9375    , 0.80645161, 0.87096774])

In [ ]:
svc_proba

array([[0.12597721, 0.87402279],
       [0.68319379, 0.31680621],
       [0.96972701, 0.03027299],
       [0.53208561, 0.46791439],
       [0.60080716, 0.39919284],
       [0.8853804 , 0.1146196 ],
       [0.23748593, 0.76251407],
       [0.22932596, 0.77067404],
       [0.0340941 , 0.9659059 ],
       [0.17510809, 0.82489191],
       [0.15918515, 0.84081485],
       [0.14960958, 0.85039042],
       [0.04391319, 0.95608681],
       [0.08340821, 0.91659179],
       [0.26908211, 0.73091789],
       [0.95466569, 0.04533431],
       [0.99452836, 0.00547164],
       [0.9855474 , 0.0144526 ],
       [0.53382762, 0.46617238],
       [0.4017143 , 0.5982857 ],
       [0.82068017, 0.17931983],
       [0.77156757, 0.22843243],
       [0.14478728, 0.85521272],
       [0.41405324, 0.58594676],
       [0.0555181 , 0.9444819 ],
       [0.98332027, 0.01667973],
       [0.52890615, 0.47109385],
       [0.48012332, 0.51987668],
       [0.11469966, 0.88530034],
       [0.11995655, 0.88004345],
       [0.

In [ ]:
svc_scores=svc_proba[:,1]
svc_scores

array([0.87402279, 0.31680621, 0.03027299, 0.46791439, 0.39919284,
       0.1146196 , 0.76251407, 0.77067404, 0.9659059 , 0.82489191,
       0.84081485, 0.85039042, 0.95608681, 0.91659179, 0.73091789,
       0.04533431, 0.00547164, 0.0144526 , 0.46617238, 0.5982857 ,
       0.17931983, 0.22843243, 0.85521272, 0.58594676, 0.9444819 ,
       0.01667973, 0.47109385, 0.51987668, 0.88530034, 0.88004345,
       0.89619659, 0.78253182, 0.00192442, 0.20397255, 0.9788859 ,
       0.91245668, 0.58715733, 0.95437448, 0.00104091, 0.6431293 ,
       0.1274714 , 0.95012418, 0.8767119 , 0.33462178, 0.01769035,
       0.00865127, 0.78777968, 0.00619317, 0.97385357, 0.74955443,
       0.98757871, 0.00675502, 0.69124623, 0.00805598, 0.06748037,
       0.70144754, 0.0261892 , 0.96104268, 0.99220093, 0.39210633,
       0.2258943 , 0.16668526, 0.80993758, 0.12662222, 0.31527738,
       0.09222602, 0.79722201, 0.46090118, 0.98242613, 0.93323197,
       0.0662195 , 0.58546203, 0.01522909, 0.22218462, 0.07907

In [ ]:
y_pred=svc_classifier.predict(x_test)
print("Actual Flood Values:")
print(y_test.values)

Actual Flood Values:
[1 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 1 0]


In [ ]:
print("Predicted Flood Values:")
print(y_pred)

Predicted Flood Values:
[1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0]


### Accuracy of our model

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\naccuracy score:%f"%(accuracy_score(y_test,y_pred)*100))
print("recall score:%f"%(recall_score(y_test,y_pred)*100))
print("roc score:%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))


accuracy score:79.166667
recall score:90.909091
roc score:80.069930
[[ 9  4]
 [ 1 10]]


# Decision Tree Classification to Predict

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc_clf=DecisionTreeClassifier()
dtc_clf.fit(x_train,y_train)
dtc_clf_acc=cross_val_score(dtc_clf,x_train_std,y_train,cv=3,scoring="accuracy",n_jobs=-1)
dtc_clf_acc

array([0.71875   , 0.64516129, 0.70967742])

In [ ]:
print("Predicted Values:")
y_pred=dtc_clf.predict(x_test)
y_pred

Predicted Values:


array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0])

In [ ]:
print("Actual Values:")
print(y_test.values)

Actual Values:
[1 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 1 0]


### Printing the Accuracy

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\naccuracy score:%f"%(accuracy_score(y_test,y_pred)*100))
print("recall score:%f"%(recall_score(y_test,y_pred)*100))
print("roc score:%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))


accuracy score:58.333333
recall score:81.818182
roc score:60.139860
[[5 8]
 [2 9]]


# Random Forest Classifier to predict

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rmf=RandomForestClassifier(max_depth=3,random_state=0)
rmf_clf=rmf.fit(x_train,y_train)
rmf_clf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
rmf_clf_acc=cross_val_score(rmf_clf,x_train_std,y_train,cv=3,scoring="accuracy",n_jobs=-1)
rmf_proba=cross_val_predict(rmf_clf,x_train_std,y_train,cv=3,method='predict_proba')

In [ ]:
rmf_clf_acc

array([0.71875   , 0.77419355, 0.80645161])

In [ ]:
rmf_proba

array([[0.37402698, 0.62597302],
       [0.66919659, 0.33080341],
       [0.55738785, 0.44261215],
       [0.64764587, 0.35235413],
       [0.64093106, 0.35906894],
       [0.66128743, 0.33871257],
       [0.35058772, 0.64941228],
       [0.44733409, 0.55266591],
       [0.39671893, 0.60328107],
       [0.3371536 , 0.6628464 ],
       [0.35243604, 0.64756396],
       [0.45223862, 0.54776138],
       [0.25753333, 0.74246667],
       [0.28724255, 0.71275745],
       [0.33060368, 0.66939632],
       [0.45956777, 0.54043223],
       [0.76736199, 0.23263801],
       [0.77231697, 0.22768303],
       [0.36476702, 0.63523298],
       [0.43888363, 0.56111637],
       [0.58089596, 0.41910404],
       [0.67460429, 0.32539571],
       [0.35653549, 0.64346451],
       [0.56644179, 0.43355821],
       [0.38865802, 0.61134198],
       [0.71861044, 0.28138956],
       [0.50480379, 0.49519621],
       [0.55662134, 0.44337866],
       [0.50677896, 0.49322104],
       [0.34738723, 0.65261277],
       [0.

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\naccuracy score:%f"%(accuracy_score(y_test,y_pred)*100))
print("recall score:%f"%(recall_score(y_test,y_pred)*100))
print("roc score:%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))


accuracy score:79.166667
recall score:72.727273
roc score:78.671329
[[11  2]
 [ 3  8]]


# Final Accuracy of our Models

### Comparing all the prediction models

In [ ]:
models = []
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
models.append(('KNN', KNeighborsClassifier()))
models.append(('LR', LogisticRegression()))
models.append(('SVC', SVC()))
models.append(('DT', DecisionTreeClassifier()))
models.append(('RF', RandomForestClassifier()))

names = []
scores = []
for name, model in models:
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    scores.append(accuracy_score(y_test, y_pred))
    names.append(name)
tr_split = pd.DataFrame({'Name': names, 'Score': scores})
tr_split

Name     Score
0  KNN  0.708333
1   LR  0.875000
2  SVC  0.791667
3   DT  0.583333
4   RF  0.833333

In [ ]:
import seaborn as sns
axis = sns.barplot(x = 'Name', y = 'Score', data =tr_split )
axis.set(xlabel='Classifier Models', ylabel='Accuracy of the Model')
for p in axis.patches:
    height = p.get_height()
    axis.text(p.get_x() + p.get_width()/2, height + 0.01, '{:1.4f}'.format(height), ha="center")

plt.show()

In [ ]:
tr_split['Score'].max()

0.875

### So we can see and choose the best model for Prediction.

# End of the Code.